### ISSUE TITLE
Working principles [Draft]

### ISSUE THREAD

**Issue by DebsDee** [w3c/devcouncil#7]
## Questions for working group

- What principles feel important for the community? Is anything missing?
- How would use these principles in our community or within our project?

### Broad participation
Not only developers create and make the web. Recognise non-traditional technological expertise a and centre the needs and expertise of designers, content creators, educators, and more.

Respect and support pre-existing communities practices.

### Accessibility and digital equity
Barriers to full community engagement should be recognised and removed. This includes but is not limited to barriers due to disability, socio-economic status, education and skillset, as well as access to digital and material infrastructure.

### Openness and transparency
Open sharing of the work and the impact of the work with web communities, make space for further contributions. Make clear who is involved and why.

### Ownership
There should be a mutual, non-extractive exchange of value 
Engaged communities should have ownership of the outcomes of their engagement with the W3C Developer Council and should be involved in determining the parameters of their engagement and decision-making mechanisms.

It's important to name and recognise power asymmetries and how these might influence ownership and self-determination for involved community groups.

### Data privacy, consent and autonomy
Respect individual and collective data autonomy, enable active consent. Consent looks like different things to different communities and it should be understood and implicitly given. Communities should be able to easily withdraw their consent and their participation at any time.

----

The above principles are influenced [Detroit Digital Justice principles](http://detroitdjc.org/principles/), which are in turn influenced by social justice principles on Access, Participation, Common Ownership, and Healthy Communities.

**Comment by lolaodelola** [comment]
This is great!! Just a few questions/notes:

On the accessibility: we might want to specifically address how we're going to interrogate our own biases, as to not exclude people due to the privileges we hold.

On consent: we should have a consent framework (e.g. https://www.consentfultech.io/) with a little additional work to think about intra-community consent (i.e. understanding that every individual is a member of an 3rd party community and members of _that_ community may have not consented to having the data held by the proxy member to be shared - we shouldn't be collecting meta data about ppl we don't have permission from)
